@tpmodul10_1302223139_HostAddress = http://localhost:5115

GET {{tpmodul10_1302223139_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{tpmodul10_1302223074_HostAddress}}/mahasiswa/
Accept: application/json

###
